In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
AdvWorksCusts = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam\AdvWorksCusts.csv')
AW_AveMonthSpend = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam\AW_AveMonthSpend.csv')
AW_BikeBuyer = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam\AW_BikeBuyer.csv')

In [3]:
Adventureworks = AdvWorksCusts.merge(AW_AveMonthSpend, on='CustomerID')

In [4]:
merged = Adventureworks.merge(AW_BikeBuyer, on='CustomerID')

In [5]:
merged

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,AveMonthSpend,BikeBuyer
0,11000,NaN,Jon,V,Yang,NaN,3761 N. 14th St,NaN,Rockhampton,Queensland,...,Professional,M,M,1,0,0,2,137947,89,0
1,11001,NaN,Eugene,L,Huang,NaN,2243 W St.,NaN,Seaford,Victoria,...,Professional,M,S,0,1,3,3,101141,117,1
2,11002,NaN,Ruben,NaN,Torres,NaN,5844 Linden Land,NaN,Hobart,Tasmania,...,Professional,M,M,1,1,3,3,91945,123,0
3,11003,NaN,Christy,NaN,Zhu,NaN,1825 Village Pl.,NaN,North Ryde,New South Wales,...,Professional,F,S,0,1,0,0,86688,50,0
4,11004,NaN,Elizabeth,NaN,Johnson,NaN,7553 Harness Circle,NaN,Wollongong,New South Wales,...,Professional,F,S,1,4,5,5,92771,95,1
5,11005,NaN,Julio,NaN,Ruiz,NaN,7305 Humphrey Drive,NaN,East Brisbane,Queensland,...,Professional,M,S,1,1,0,0,103199,78,1
6,11006,NaN,Janet,G,Alvarez,NaN,2612 Berry Dr,NaN,Matraville,New South Wales,...,Professional,F,S,1,1,0,0,84756,54,1
7,11007,NaN,Marco,NaN,Mehta,NaN,942 Brook Street,NaN,Warrnambool,Victoria,...,Professional,M,M,1,2,3,3,109759,130,1
8,11008,NaN,Rob,NaN,Verhoff,NaN,624 Peabody Road,NaN,Bendigo,Victoria,...,Professional,F,S,1,3,4,4,88005,85,1
9,11009,NaN,Shannon,C,Carlson,NaN,3839 Northgate Road,NaN,Hervey Bay,Queensland,...,Professional,M,S,0,1,0,0,106399,74,0
10,11010,NaN,Jacquelyn,C,Suarez,NaN,7800 Corrinne Court,NaN,East Brisbane,Queensland,...,Professional,F,S,0,1,0,0,81294,49,0
11,11011,NaN,Curtis,NaN,Lu,NaN,1224 Shoenic,NaN,East Brisbane,Queensland,...,Professional,M,M,1,4,4,4,94029,146,1
12,11012,NaN,Lauren,M,Walker,NaN,4785 Scott Street,NaN,Bremerton,Washington,...,Management,F,M,1,2,0,2,99245,55,1
13,11013,NaN,Ian,M,Jenkins,NaN,7902 Hudson Ave.,NaN,Lebanon,Oregon,...,Management,M,M,1,3,0,2,115859,84,0
14,11014,NaN,Sydney,NaN,Bennett,NaN,9011 Tank Drive,NaN,Redmond,Washington,...,Management,F,S,0,3,0,3,105157,49,0
15,11015,NaN,Chloe,NaN,Young,NaN,244 Willow Pass Road,NaN,Burbank,California,...,Skilled Manual,F,S,0,1,0,0,40011,39,0
16,11016,NaN,Wyatt,L,Hill,NaN,9666 Northridge Ct.,NaN,Imperial Beach,California,...,Skilled Manual,M,M,1,1,0,0,46808,68,0
17,11019,NaN,Luke,L,Lal,NaN,7832 Landing Dr,NaN,Langley,British Columbia,...,Skilled Manual,M,S,0,2,0,0,49455,64,1
18,11020,NaN,Jordan,C,King,NaN,7156 Rose Dr.,NaN,Metchosin,British Columbia,...,Skilled Manual,M,S,0,2,0,0,43857,64,0
19,11023,NaN,Seth,M,Edwards,NaN,4499 Valley Crest,NaN,Bellflower,California,...,Skilled Manual,M,M,1,1,0,0,50046,71,0
20,11024,NaN,Russell,NaN,Xie,NaN,8734 Oxford Place,NaN,Concord,California,...,Skilled Manual,M,M,1,2,0,0,91276,77,0
21,11025,NaN,Alejandro,NaN,Beck,NaN,2596 Franklin Canyon Road,NaN,Hawthorne,Queensland,...,Clerical,M,M,1,2,1,2,24334,70,0
22,11026,NaN,Harold,NaN,Sai,NaN,8211 Leeds Ct.,NaN,Goulburn,New South Wales,...,Clerical,M,S,0,2,0,2,61905,63,0
23,11027,NaN,Jessie,R,Zhao,NaN,213 Valencia Place,NaN,Warrnambool,Victoria,...,Clerical,M,M,1,2,0,2,49349,76,0
24,11028,NaN,Jill,NaN,Jimenez,NaN,9111 Rose Ann Ave,NaN,St. Leonards,New South Wales,...,Clerical,F,M,1,2,0,2,44068,43,0
25,11031,NaN,Theresa,G,Ramos,NaN,6465 Detroit Ave.,NaN,Matraville,New South Wales,...,Skilled Manual,F,M,1,2,0,4,18843,43,0
26,11032,NaN,Denise,NaN,Stone,NaN,626 Bentley Street,NaN,Melbourne,Victoria,...,Skilled Manual,F,M,1,2,0,4,15861,42,0
27,11033,NaN,Jaime,NaN,Nath,NaN,5927 Rainbow Dr,NaN,Milsons Point,New South Wales,...,Skilled Manual,M,M,1,2,0,4,35822,58,0
28,11034,NaN,Ebony,NaN,Gonzalez,NaN,5167 Condor Place,NaN,North Sydney,New South Wales,...,Skilled Manual,F,M,1,2,0,4,29017,39,0
29,11035,NaN,Wendy,NaN,Dominguez,NaN,1873 Mt. Whitney Dr,NaN,Cranbourne,Victoria,...,Clerical,F,M,1,2,1,2,11721,50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17179,29451,NaN,Geoffrey,A,Lopez,NaN,"5911, rue des Ecoles",NaN,Paris,Seine (Paris),...,Manual,M,S,0,1,0,3,16989,55,0
17180,29452,NaN,Meredith,J,Romero,NaN,8335 West Hookston Road,NaN,Darlinghurst,New South Wales,...,Manual,F,S,1,1,0,0,20215,38,0
17181,29454,NaN,Victoria,NaN,Bradley,NaN,1227 Wesley Court,NaN,Caloundra,Queensland,...,Manual,F,M,1,1,0,0,23245,49,0
17182,29455,NaN,Dawn,D,Zeng,NaN,460 Skyline Dr,NaN,Sunbury,Victoria,...,Manual,F,M,1,1,0,0,27082,44,0
17183,29456,NaN,Lindsay,NaN,She,NaN,8241 Seawind Dr.,NaN,Lane Cove,New South Wales,...,Manual,F,S,1,1,0,0,29588,38,0
17184,29457,NaN,Cynthia,NaN,Kapoor,NaN,7045 Creekside Drive,NaN,Cranbourne,Victoria,...,Manual,F,S,0,1,0,0,20689,42,1
17185,29458,NaN,Danny,M,Moreno,NaN,1170 Shaw Rd,NaN,St. Leonards,New South Wales,...,Manual,M,S,1,1,0,0,12684,57,0
17186,29460,NaN,Andres,E,Chander,NaN,6030 Double Court,NaN,South Melbourne,Victoria,...,Manual,M,M,0,2,0,0,13526,55,0
17187,29461,NaN,Colin,C,Xu,NaN,1654 Bonari Court,NaN,Findon,South Australia,...,Manual,M,M,1,2,0,0,17045,62,0
17188,29462,NaN,Clinton,NaN,Hernandez,NaN,1733 Thistle Circle,NaN,Rockhampton,Queensland,...,Clerical,M,S,1,0,0,0,39354,66,0
17189,29463,NaN,Lucas,NaN,Gonzales,NaN,6908 Woodchuck Pl.,NaN,Gold Coast,Queensland,...,Manual,M,S,1,0,1,1,21359,67,0
17190,29464,NaN,Eugene,NaN,Gao,NaN,4581 Coldwater Drive,NaN,Rockhampton,Queensland,...,Manual,M,S,0,0,1,1,12002,67,0
17191,29465,NaN,Roy,NaN,Gill,NaN,4072 South Hampton Road,NaN,Matraville,New South Wales,...,Manual,M,S,1,0,0,0,22109,64,0
17192,29466,NaN,Lance,NaN,Jimenez,NaN,Auf Der Steige 532,NaN,Solingen,Nordrhein-Westfalen,...,Clerical,M,M,1,0,0,1,59132,64,0
17193,29467,NaN,Monica,J,Mehta,NaN,Bundesallee 2461,NaN,Sulzbach Taunus,Saarland,...,Clerical,F,M,1,0,0,4,75167,57,0
17194,29468,NaN,Jacqueline,H,Morris,NaN,6934 Santa Cruz Dr.,NaN,Cheltenham,England,...,Clerical,F,M,0,0,0,4,62297,53,0
17195,29469,NaN,Dominique,M,Saunders,NaN,3792 Westwood Ct.,NaN,Oxon,England,...,Clerical,F,M,0,0,0,3,65669,56,0
17196,29470,NaN,Nathan,NaN,Roberts,NaN,"29, boulevard Beau Marchais",NaN,Drancy,Seine Saint Denis,...,Manual,M,S,0,1,1,1,28464,69,1
17197,29471,NaN,Dana,NaN,Ortega,NaN,"80, rue de Fontfroide",NaN,Dunkerque,Nord,...,Manual,F,S,0,1,1,1,28506,49,0
17198,29472,NaN,Lacey,M,Sharma,NaN,"21, avenue Reille",NaN,Paris,Seine (Paris),...,Manual,F,M,0,1,1,1,11848,45,0
17199,29473,NaN,Carmen,J,Subram,NaN,6467 Buena Vista,NaN,Oxford,England,...,Manual,F,S,0,0,1,1,20048,43,0
17200,29474,NaN,Jaime,B,Raje,NaN,Potsdamer Straße 646,NaN,Saarbrücken,Saarland,...,Manual,M,M,0,1,0,2,24761,64,0
17201,29475,NaN,Jared,A,Ward,NaN,Erftplatz 876,NaN,Hamburg,Hamburg,...,Manual,M,S,0,1,0,2,29938,61,0
17202,29476,NaN,Elizabeth,NaN,Bradley,NaN,Nonnendamm 2,NaN,Hamburg,Hamburg,...,Manual,F,M,0,1,0,2,18670,48,0
17203,29477,NaN,Neil,N,Ruiz,NaN,P.O. Box 9178,NaN,London,England,...,Manual,M,M,0,1,0,2,22992,67,0
17204,29478,NaN,Darren,D,Carlson,NaN,5240 Premier Pl.,NaN,Stoke-on-Trent,England,...,Clerical,M,S,1,0,0,3,45986,65,0
17205,29479,NaN,Tommy,L,Tang,NaN,"111, rue Maillard",NaN,Versailles,Yveline,...,Clerical,M,M,1,0,0,1,80049,77,0
17206,29480,NaN,Nina,W,Raji,NaN,9 Katherine Drive,NaN,London,England,...,Clerical,F,S,1,0,0,3,60417,48,1
17207,29481,NaN,Ivan,NaN,Suri,NaN,Knaackstr 4,NaN,Hof,Bayern,...,Clerical,M,S,0,0,0,3,66653,65,0
17208,29482,NaN,Clayton,NaN,Zhang,NaN,"1080, quai de Grenelle",NaN,Saint Ouen,Charente-Maritime,...,Clerical,M,M,1,0,0,3,59736,72,0

In [6]:
merged.drop(['Title','Suffix','AddressLine2'], axis = 1, inplace=True)

In [7]:
merged.CustomerID.unique().shape

(16404,)

In [8]:
merged.shape

(17209, 22)

In [9]:
merged['AveMonthSpend'].mean()

72.49462490557266

In [10]:
list(merged.columns.values)

['CustomerID',
 'FirstName',
 'MiddleName',
 'LastName',
 'AddressLine1',
 'City',
 'StateProvinceName',
 'CountryRegionName',
 'PostalCode',
 'PhoneNumber',
 'BirthDate',
 'Education',
 'Occupation',
 'Gender',
 'MaritalStatus',
 'HomeOwnerFlag',
 'NumberCarsOwned',
 'NumberChildrenAtHome',
 'TotalChildren',
 'YearlyIncome',
 'AveMonthSpend',
 'BikeBuyer']

In [11]:
merged.drop_duplicates(subset ='CustomerID',keep='last', inplace=True)

In [12]:
merged

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,...,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,AveMonthSpend,BikeBuyer
0,11000,Jon,V,Yang,3761 N. 14th St,Rockhampton,Queensland,Australia,4700,1 (11) 500 555-0162,...,Professional,M,M,1,0,0,2,137947,89,0
1,11001,Eugene,L,Huang,2243 W St.,Seaford,Victoria,Australia,3198,1 (11) 500 555-0110,...,Professional,M,S,0,1,3,3,101141,117,1
2,11002,Ruben,NaN,Torres,5844 Linden Land,Hobart,Tasmania,Australia,7001,1 (11) 500 555-0184,...,Professional,M,M,1,1,3,3,91945,123,0
3,11003,Christy,NaN,Zhu,1825 Village Pl.,North Ryde,New South Wales,Australia,2113,1 (11) 500 555-0162,...,Professional,F,S,0,1,0,0,86688,50,0
4,11004,Elizabeth,NaN,Johnson,7553 Harness Circle,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0131,...,Professional,F,S,1,4,5,5,92771,95,1
5,11005,Julio,NaN,Ruiz,7305 Humphrey Drive,East Brisbane,Queensland,Australia,4169,1 (11) 500 555-0151,...,Professional,M,S,1,1,0,0,103199,78,1
6,11006,Janet,G,Alvarez,2612 Berry Dr,Matraville,New South Wales,Australia,2036,1 (11) 500 555-0184,...,Professional,F,S,1,1,0,0,84756,54,1
7,11007,Marco,NaN,Mehta,942 Brook Street,Warrnambool,Victoria,Australia,3280,1 (11) 500 555-0126,...,Professional,M,M,1,2,3,3,109759,130,1
8,11008,Rob,NaN,Verhoff,624 Peabody Road,Bendigo,Victoria,Australia,3550,1 (11) 500 555-0164,...,Professional,F,S,1,3,4,4,88005,85,1
9,11009,Shannon,C,Carlson,3839 Northgate Road,Hervey Bay,Queensland,Australia,4655,1 (11) 500 555-0110,...,Professional,M,S,0,1,0,0,106399,74,0
10,11010,Jacquelyn,C,Suarez,7800 Corrinne Court,East Brisbane,Queensland,Australia,4169,1 (11) 500 555-0169,...,Professional,F,S,0,1,0,0,81294,49,0
11,11011,Curtis,NaN,Lu,1224 Shoenic,East Brisbane,Queensland,Australia,4169,1 (11) 500 555-0117,...,Professional,M,M,1,4,4,4,94029,146,1
12,11012,Lauren,M,Walker,4785 Scott Street,Bremerton,Washington,United States,98312,717-555-0164,...,Management,F,M,1,2,0,2,99245,55,1
13,11013,Ian,M,Jenkins,7902 Hudson Ave.,Lebanon,Oregon,United States,97355,817-555-0185,...,Management,M,M,1,3,0,2,115859,84,0
14,11014,Sydney,NaN,Bennett,9011 Tank Drive,Redmond,Washington,United States,98052,431-555-0156,...,Management,F,S,0,3,0,3,105157,49,0
15,11015,Chloe,NaN,Young,244 Willow Pass Road,Burbank,California,United States,91502,208-555-0142,...,Skilled Manual,F,S,0,1,0,0,40011,39,0
16,11016,Wyatt,L,Hill,9666 Northridge Ct.,Imperial Beach,California,United States,91932,135-555-0171,...,Skilled Manual,M,M,1,1,0,0,46808,68,0
17,11019,Luke,L,Lal,7832 Landing Dr,Langley,British Columbia,Canada,V3A 4R2,262-555-0112,...,Skilled Manual,M,S,0,2,0,0,49455,64,1
18,11020,Jordan,C,King,7156 Rose Dr.,Metchosin,British Columbia,Canada,V9,550-555-0163,...,Skilled Manual,M,S,0,2,0,0,43857,64,0
19,11023,Seth,M,Edwards,4499 Valley Crest,Bellflower,California,United States,90706,452-555-0188,...,Skilled Manual,M,M,1,1,0,0,50046,71,0
20,11024,Russell,NaN,Xie,8734 Oxford Place,Concord,California,United States,94519,746-555-0186,...,Skilled Manual,M,M,1,2,0,0,91276,77,0
21,11025,Alejandro,NaN,Beck,2596 Franklin Canyon Road,Hawthorne,Queensland,Australia,4171,1 (11) 500 555-0178,...,Clerical,M,M,1,2,1,2,24334,70,0
22,11026,Harold,NaN,Sai,8211 Leeds Ct.,Goulburn,New South Wales,Australia,2580,1 (11) 500 555-0131,...,Clerical,M,S,0,2,0,2,61905,63,0
23,11027,Jessie,R,Zhao,213 Valencia Place,Warrnambool,Victoria,Australia,3280,1 (11) 500 555-0184,...,Clerical,M,M,1,2,0,2,49349,76,0
24,11028,Jill,NaN,Jimenez,9111 Rose Ann Ave,St. Leonards,New South Wales,Australia,2065,1 (11) 500 555-0116,...,Clerical,F,M,1,2,0,2,44068,43,0
25,11031,Theresa,G,Ramos,6465 Detroit Ave.,Matraville,New South Wales,Australia,2036,1 (11) 500 555-0195,...,Skilled Manual,F,M,1,2,0,4,18843,43,0
26,11032,Denise,NaN,Stone,626 Bentley Street,Melbourne,Victoria,Australia,3000,1 (11) 500 555-0169,...,Skilled Manual,F,M,1,2,0,4,15861,42,0
27,11033,Jaime,NaN,Nath,5927 Rainbow Dr,Milsons Point,New South Wales,Australia,2061,1 (11) 500 555-0137,...,Skilled Manual,M,M,1,2,0,4,35822,58,0
28,11034,Ebony,NaN,Gonzalez,5167 Condor Place,North Sydney,New South Wales,Australia,2055,1 (11) 500 555-0136,...,Skilled Manual,F,M,1,2,0,4,29017,39,0
29,11035,Wendy,NaN,Dominguez,1873 Mt. Whitney Dr,Cranbourne,Victoria,Australia,3977,1 (11) 500 555-0177,...,Clerical,F,M,1,2,1,2,11721,50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17179,29451,Geoffrey,A,Lopez,"5911, rue des Ecoles",Paris,Seine (Paris),France,75016,1 (11) 500 555-0143,...,Manual,M,S,0,1,0,3,16989,55,0
17180,29452,Meredith,J,Romero,8335 West Hookston Road,Darlinghurst,New South Wales,Australia,2010,1 (11) 500 555-0187,...,Manual,F,S,1,1,0,0,20215,38,0
17181,29454,Victoria,NaN,Bradley,1227 Wesley Court,Caloundra,Queensland,Australia,4551,1 (11) 500 555-0125,...,Manual,F,M,1,1,0,0,23245,49,0
17182,29455,Dawn,D,Zeng,460 Skyline Dr,Sunbury,Victoria,Australia,3429,1 (11) 500 555-0161,...,Manual,F,M,1,1,0,0,27082,44,0
17183,29456,Lindsay,NaN,She,8241 Seawind Dr.,Lane Cove,New South Wales,Australia,1597,1 (11) 500 555-0142,...,Manual,F,S,1,1,0,0,29588,38,0
17184,29457,Cynthia,NaN,Kapoor,7045 Creekside Drive,Cranbourne,Victoria,Australia,3977,1 (11) 500 555-0180,...,Manual,F,S,0,1,0,0,20689,42,1
17185,29458,Danny,M,Moreno,1170 Shaw Rd,St. Leonards,New South Wales,Australia,2065,1 (11) 500 555-0188,...,Manual,M,S,1,1,0,0,12684,57,0
17186,29460,Andres,E,Chander,6030 Double Court,South Melbourne,Victoria,Australia,3205,1 (11) 500 555-0133,...,Manual,M,M,0,2,0,0,13526,55,0
17187,29461,Colin,C,Xu,1654 Bonari Court,Findon,South Australia,Australia,5023,1 (11) 500 555-0146,...,Manual,M,M,1,2,0,0,17045,62,0
17188,29462,Clinton,NaN,Hernandez,1733 Thistle Circle,Rockhampton,Queensland,Australia,4700,1 (11) 500 555-0189,...,Clerical,M,S,1,0,0,0,39354,66,0
17189,29463,Lucas,NaN,Gonzales,6908 Woodchuck Pl.,Gold Coast,Queensland,Australia,4217,1 (11) 500 555-0172,...,Manual,M,S,1,0,1,1,21359,67,0
17190,29464,Eugene,NaN,Gao,4581 Coldwater Drive,Rockhampton,Queensland,Australia,4700,1 (11) 500 555-0177,...,Manual,M,S,0,0,1,1,12002,67,0
17191,29465,Roy,NaN,Gill,4072 South Hampton Road,Matraville,New South Wales,Australia,2036,1 (11) 500 555-0110,...,Manual,M,S,1,0,0,0,22109,64,0
17192,29466,Lance,NaN,Jimenez,Auf Der Steige 532,Solingen,Nordrhein-Westfalen,Germany,42651,1 (11) 500 555-0126,...,Clerical,M,M,1,0,0,1,59132,64,0
17193,29467,Monica,J,Mehta,Bundesallee 2461,Sulzbach Taunus,Saarland,Germany,66272,1 (11) 500 555-0121,...,Clerical,F,M,1,0,0,4,75167,57,0
17194,29468,Jacqueline,H,Morris,6934 Santa Cruz Dr.,Cheltenham,England,United Kingdom,GL50,1 (11) 500 555-0131,...,Clerical,F,M,0,0,0,4,62297,53,0
17195,29469,Dominique,M,Saunders,3792 Westwood Ct.,Oxon,England,United Kingdom,OX16 8RS,1 (11) 500 555-0172,...,Clerical,F,M,0,0,0,3,65669,56,0
17196,29470,Nathan,NaN,Roberts,"29, boulevard Beau Marchais",Drancy,Seine Saint Denis,France,93700,1 (11) 500 555-0111,...,Manual,M,S,0,1,1,1,28464,69,1
17197,29471,Dana,NaN,Ortega,"80, rue de Fontfroide",Dunkerque,Nord,France,59140,1 (11) 500 555-0148,...,Manual,F,S,0,1,1,1,28506,49,0
17198,29472,Lacey,M,Sharma,"21, avenue Reille",Paris,Seine (Paris),France,75003,1 (11) 500 555-0178,...,Manual,F,M,0,1,1,1,11848,45,0
17199,29473,Carmen,J,Subram,6467 Buena Vista,Oxford,England,United Kingdom,OX1,1 (11) 500 555-0129,...,Manual,F,S,0,0,1,1,20048,43,0
17200,29474,Jaime,B,Raje,Potsdamer Straße 646,Saarbrücken,Saarland,Germany,66001,1 (11) 500 555-0174,...,Manual,M,M,0,1,0,2,24761,64,0
17201,29475,Jared,A,Ward,Erftplatz 876,Hamburg,Hamburg,Germany,20354,1 (11) 500 555-0135,...,Manual,M,S,0,1,0,2,29938,61,0
17202,29476,Elizabeth,NaN,Bradley,Nonnendamm 2,Hamburg,Hamburg,Germany,20354,1 (11) 500 555-0177,...,Manual,F,M,0,1,0,2,18670,48,0
17203,29477,Neil,N,Ruiz,P.O. Box 9178,London,England,United Kingdom,W10 6BL,1 (11) 500 555-0114,...,Manual,M,M,0,1,0,2,22992,67,0
17204,29478,Darren,D,Carlson,5240 Premier Pl.,Stoke-on-Trent,England,United Kingdom,AS23,1 (11) 500 555-0132,...,Clerical,M,S,1,0,0,3,45986,65,0
17205,29479,Tommy,L,Tang,"111, rue Maillard",Versailles,Yveline,France,78000,1 (11) 500 555-0136,...,Clerical,M,M,1,0,0,1,80049,77,0
17206,29480,Nina,W,Raji,9 Katherine Drive,London,England,United Kingdom,SW19 3RU,1 (11) 500 555-0146,...,Clerical,F,S,1,0,0,3,60417,48,1
17207,29481,Ivan,NaN,Suri,Knaackstr 4,Hof,Bayern,Germany,95010,1 (11) 500 555-0144,...,Clerical,M,S,0,0,0,3,66653,65,0
17208,29482,Clayton,NaN,Zhang,"1080, quai de Grenelle",Saint Ouen,Charente-Maritime,France,17490,1 (11) 500 555-0137,...,Clerical,M,M,1,0,0,3,59736,72,0

In [13]:
print (merged.shape)
print (merged.CustomerID.unique().shape)

(16404, 22)
(16404,)

In [14]:
from dateutil.parser import parse 
from datetime import datetime

def generate_age(customer_info, format):
    collection_day = birthday = datetime(2019, 1, 1, 0, 0, 0)
    age = []
    for index, row in customer_info.iterrows():
        conv = datetime.strptime(row['BirthDate'], format)
        age.append(int((collection_day - conv).days/365))
    return age

In [15]:

merged['Age'] = generate_age(merged, '%Y-%m-%d')

In [16]:
merged.columns

Index(['CustomerID', 'FirstName', 'MiddleName', 'LastName', 'AddressLine1',
       'City', 'StateProvinceName', 'CountryRegionName', 'PostalCode',
       'PhoneNumber', 'BirthDate', 'Education', 'Occupation', 'Gender',
       'MaritalStatus', 'HomeOwnerFlag', 'NumberCarsOwned',
       'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome',
       'AveMonthSpend', 'BikeBuyer', 'Age'],
      dtype='object')

In [17]:
merged['Age'] += 1

In [18]:
x = merged.loc[:,['CustomerID','YearlyIncome','Gender','Age']].values

In [19]:
x

array([[11000, 137947, 'M', 53],
       [11001, 101141, 'M', 54],
       [11002, 91945, 'M', 54],
       ...,
       [29480, 60417, 'F', 59],
       [29481, 66653, 'M', 60],
       [29482, 59736, 'M', 60]], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,2] = labelencoder_x.fit_transform(x[:,2])
onehotencoder = OneHotEncoder(categorical_features=[2])
x = onehotencoder.fit_transform(x).toarray()

In [21]:
x

array([[0.00000e+00, 1.00000e+00, 1.10000e+04, 1.37947e+05, 5.30000e+01],
       [0.00000e+00, 1.00000e+00, 1.10010e+04, 1.01141e+05, 5.40000e+01],
       [0.00000e+00, 1.00000e+00, 1.10020e+04, 9.19450e+04, 5.40000e+01],
       ...,
       [1.00000e+00, 0.00000e+00, 2.94800e+04, 6.04170e+04, 5.90000e+01],
       [0.00000e+00, 1.00000e+00, 2.94810e+04, 6.66530e+04, 6.00000e+01],
       [0.00000e+00, 1.00000e+00, 2.94820e+04, 5.97360e+04, 6.00000e+01]])

In [22]:
y = merged.iloc[:,-2].values

In [23]:
y

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [24]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=0)

C:\ProgramData\Anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test =sc.transform(x_test)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
classifier = LogisticRegression(random_state = 0)

In [28]:
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [29]:
y_pred = classifier.predict(x_test)

In [30]:
y_test
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
print(y_test)
print(y_pred)

[1 0 1 ... 0 0 0]
[1 0 0 ... 0 0 0]

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
cm = confusion_matrix(y_test, y_pred)

In [34]:
cm

array([[2464,  290],
       [ 946,  401]], dtype=int64)

In [35]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski',p=2 )

In [36]:
classifier2.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [37]:
y_predd = classifier2.predict(x_test)

In [38]:
cm2 = confusion_matrix(y_test, y_predd)

In [39]:
cm2

array([[2306,  448],
       [ 661,  686]], dtype=int64)

In [40]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [41]:
msr = mean_squared_error(y_test, y_pred)

In [42]:
msr

0.3013899049012436

In [43]:
RMSE = sqrt(msr)

In [44]:
RMSE

0.5489898950811787

In [45]:
msr2 = mean_squared_error(y_test, y_predd)

In [46]:
msr2

0.2704218483296757

In [47]:
RMSE2 = sqrt(msr2)

In [48]:
RMSE2

0.5200210075849587

In [49]:
testdata = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam-Test\AW_test.csv')

In [50]:
print (testdata.shape)
print (testdata.CustomerID.unique().shape)

(500, 23)
(500,)

In [51]:
from dateutil.parser import parse 
from datetime import datetime

def generate_age(customer_info, format):
    collection_day = birthday = datetime(2019, 1, 1, 0, 0, 0)
    age = []
    for index, row in customer_info.iterrows():
        conv = datetime.strptime(row['BirthDate'], format)
        age.append(int((collection_day - conv).days/365))
    return age

In [52]:
testdata['Age'] = generate_age(testdata, '%m/%d/%Y')

In [53]:
testdata['Age'] += 1

In [54]:
testdata_x = testdata.loc[:,['CustomerID','YearlyIncome','Gender','Age']].values

In [55]:
testdata_x

array([[18988, 86931, 'F', 75],
       [29135, 100125, 'M', 55],
       [12156, 103985, 'F', 86],
       ...,
       [14500, 138097, 'F', 82],
       [22223, 101465, 'F', 62],
       [29068, 19108, 'F', 72]], dtype=object)

In [56]:

testdata_x[:,2] = labelencoder_x.fit_transform(testdata_x[:,2])
onehotencoder = OneHotEncoder(categorical_features=[2])
testdata_x = onehotencoder.fit_transform(testdata_x).toarray()

In [57]:

scaled_instances = sc.transform(testdata_x)
print(scaled_instances)

[[ 1.01729991 -1.01729991 -0.22663369  0.21837654  1.56932277]
 [-0.98299429  0.98299429  1.67036025  0.55032799 -0.21038051]
 [ 1.01729991 -1.01729991 -1.50388437  0.64744278  2.54815958]
 ...
 [ 1.01729991 -1.01729991 -1.06567073  1.5056759   2.19221892]
 [ 1.01729991 -1.01729991  0.37815348  0.58404142  0.41251564]
 [ 1.01729991 -1.01729991  1.65783452 -1.48800082  1.30236728]]

In [61]:
BikeBuyer = classifier2.predict(scaled_instances)

In [62]:
BikeBuyer

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [63]:
%pastebin 1-62

'http://dpaste.com/3DVS1CF'

In [65]:
np.savetxt('bikebuyerpred.csv', BikeBuyer, delimiter=',')